version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000" # Change this to your app's port if necessary
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
