version: "3.8"

services:
  secure-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: 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
        REPO_URL: https://github.com/JakeScottSalt/dockertest.git
    environment:
      - NODE_ENV=production
    networks:
      - secure-net

networks:
  secure-net:
    driver: bridge
