version: "3.8"

services:
  secure-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: your_token_here
        REPO_URL: github.com/yourusername/yourrepo.git
    environment:
      - NODE_ENV=production
    networks:
      - secure-net

networks:
  secure-net:
    driver: bridge
